"""Test whether any prior state predicts the next round.

This is where the accumulation/release hypothesis is decided. The tests are
written to be able to fail: `TestDetectionPower` runs the identical harness
against a tape with a deliberately planted dependency and asserts that it is
found. Without that control, "no edge detected" would be worthless.
"""

from __future__ import annotations

import pytest

from conftest import synthetic_dependent_tape, synthetic_fair_tape
from research import independence

pytestmark = pytest.mark.tape


class TestDetectionPower:
    """Controls proving the harness can find a real edge."""

    def test_planted_dependency_is_detected(self):
        tape = synthetic_dependent_tape()
        result = independence.test_pressure_release(tape, lookback=40, horizon=10)
        assert result["hypothesis_supported"], (
            "the harness failed to detect a deliberately planted drought->moonshot "
            "rule, so any 'no edge' verdict it produces is meaningless"
        )
        assert "drought_no_10x_in_lookback" in result["actionable_signals"]

    def test_planted_serial_dependence_is_detected(self):
        tape = synthetic_dependent_tape()
        multipliers = [r["multiplier"] for r in tape]
        result = independence.gap_independence(multipliers)
        # Forced releases cap the gap, collapsing its variance.
        assert result["gap_cv"] < 0.9

    def test_fair_synthetic_tape_shows_no_edge(self):
        tape = synthetic_fair_tape()
        result = independence.test_pressure_release(tape, lookback=40, horizon=10)
        assert not result["hypothesis_supported"], (
            "the harness reported an edge on a tape generated by inverting the "
            "fair CDF, so it is producing false positives"
        )


class TestPressureReleaseOnRealTape:
    @pytest.fixture(scope="class")
    def result(self, rounds):
        return independence.test_pressure_release(rounds, lookback=40, horizon=10)

    def test_no_pressure_signal_is_actionable(self, result):
        assert not result["hypothesis_supported"], (
            f"signals {result['actionable_signals']} appear to predict releases; "
            "this would be an RNG defect and must be reproduced independently"
        )

    def test_all_five_signals_were_exercised(self, result):
        assert result["signals_tested"] == 5
        for entry in result["results"]:
            assert entry.get("fired", 0) > 0, f"signal {entry['signal']} never fired"

    def test_lift_is_within_noise_for_every_signal(self, result):
        for entry in result["results"]:
            if "lift" not in entry:
                continue
            assert abs(entry["lift"]) < 0.15, (
                f"{entry['signal']} shows a lift of {entry['lift']}, which is large "
                "enough to warrant investigation"
            )

    def test_permutation_tests_do_not_reject(self, result):
        surviving = [
            entry["signal"]
            for entry in result["results"]
            if entry.get("permutation_p_value", 1.0) < 0.01
        ]
        assert not surviving, f"signals surviving permutation: {surviving}"

    def test_next_round_band_is_independent_of_every_signal(self, result):
        for entry in result["results"]:
            band_test = entry.get("next_round_band_test") or {}
            if not band_test.get("bins"):
                continue
            assert not band_test.get("dependent"), (
                f"{entry['signal']} shifts the next round's band distribution "
                f"(p={band_test.get('p_value')})"
            )


class TestSerialStructure:
    @pytest.fixture(scope="class")
    def result(self, multipliers):
        return independence.serial_structure(multipliers, max_lag=20)

    def test_rounds_are_not_serially_dependent(self, result):
        assert not result["serially_dependent"], (
            f"Ljung-Box rejects independence (Q={result['ljung_box']}, "
            f"p={result['ljung_box_p_value']})"
        )

    def test_few_lags_exceed_the_white_noise_bound(self, result):
        # Roughly one lag in twenty may exceed the 95% bound by chance.
        assert len(result["lags_outside_bound"]) <= 3, (
            f"lags outside the bound: {result['lags_outside_bound']}"
        )

    def test_no_single_lag_shows_strong_correlation(self, result):
        worst = max(abs(v) for v in result["autocorrelation"].values())
        assert worst < 0.10, f"strongest autocorrelation is {worst}"

    def test_high_rounds_do_not_cluster(self, result):
        runs = result["runs_test_moonshot"]
        if runs["n"] < 50:
            pytest.skip("too few observations for the moonshot runs test")
        assert runs["p_value"] > 0.01, (
            f"moonshots cluster or alternate more than chance allows (p={runs['p_value']})"
        )

    def test_median_split_shows_no_streaking(self, result):
        assert result["runs_test_median"]["p_value"] > 0.01


class TestGapIndependence:
    @pytest.fixture(scope="class")
    def result(self, multipliers):
        return independence.gap_independence(multipliers)

    def test_enough_events_to_analyse(self, result):
        assert result.get("events", 0) >= 30

    def test_drought_does_not_predict_the_next_gap(self, result):
        assert not result["drought_predicts_next_gap"], (
            "the length of a drought predicts the next one, contradicting "
            f"independence (p={result['permutation_p_value']})"
        )

    def test_gaps_are_geometric(self, result):
        # A geometric gap distribution has a coefficient of variation near 1.
        assert 0.7 < result["gap_cv"] < 1.3, (
            f"gap CV {result['gap_cv']} is far from the geometric value of ~1, "
            "which would mean events are clustered or unnaturally regular"
        )

    def test_waiting_does_not_shorten_the_wait(self, result):
        after_long = result["mean_gap_after_long_drought"]
        after_short = result["mean_gap_after_short_drought"]
        if after_long is None or after_short is None:
            pytest.skip("insufficient gap data")
        # The gambler's fallacy predicts a much shorter wait after a drought.
        ratio = after_long / after_short
        assert 0.6 < ratio < 1.6, (
            f"mean gap after a long drought is {ratio:.2f}x the gap after a short "
            "one, which is the 'it is due' effect and should not exist"
        )


class TestConditionalBandTest:
    def test_unrelated_flag_is_not_dependent(self, multipliers):
        flags = [index % 3 == 0 for index in range(len(multipliers))]
        result = independence.conditional_band_test(multipliers, flags)
        assert not result["dependent"]

    def test_perfectly_informative_flag_is_dependent(self):
        # Flag is true exactly when the round is a moonshot.
        values = [1.5, 30.0] * 400
        flags = [v >= 20.0 for v in values]
        result = independence.conditional_band_test(values, flags)
        assert result["dependent"]

    def test_mismatched_lengths_are_rejected(self):
        with pytest.raises(ValueError):
            independence.conditional_band_test([1.0, 2.0], [True])

    def test_sparse_arm_returns_neutral(self, multipliers):
        flags = [index < 5 for index in range(len(multipliers))]
        result = independence.conditional_band_test(multipliers, flags)
        assert not result["dependent"]


class TestCausality:
    """A signal must never be able to see its own outcome."""

    def test_signal_window_cannot_reach_the_outcome(self, rounds):
        seen_max = []

        def recording_signal(window):
            seen_max.append(max(window))
            return False

        subset = rounds[:3000]
        independence.signal_lift(
            subset, recording_signal, "probe", lookback=40, horizon=10, permutations=10
        )
        # The harness must have called the signal on windows only.
        assert len(seen_max) == len(subset) - 40 - 10

    def test_future_peeking_signal_is_flagged(self, rounds):
        """A signal that cheats must be detected, confirming the gates work."""
        multipliers = [float(r["multiplier"]) for r in rounds[:6000]]
        oracle_rounds = rounds[:6000]

        # This signal is given the answer through a closure over the full tape.
        def oracle(window):
            index = len(oracle.calls) + 40
            oracle.calls.append(index)
            future = multipliers[index : index + 10]
            return bool(future) and max(future) >= 20.0

        oracle.calls = []

        result = independence.signal_lift(
            oracle_rounds, oracle, "oracle", lookback=40, horizon=10, permutations=500
        )
        assert result["actionable"], (
            "a signal with access to the outcome must be flagged as actionable; "
            "if it is not, the gates are too strict to detect a real edge"
        )
        assert result["lift"] > 0.5
