"""Validate the Eagle Eye exports against the semantic layer.

These tests are the data contract. They prove the CSVs are machine-generated by
this codebase, which is what allows later tests to treat the tape as evidence
rather than as an unverified file.
"""

from __future__ import annotations

import math

import pytest

from momento import linguistics as ling
from research import loader

pytestmark = pytest.mark.tape


class TestCleanTapeIntegrity:
    def test_tape_loads_with_no_invariant_violations(self, clean_tape):
        assert clean_tape.violations == [], (
            f"export disagrees with the semantic layer: {clean_tape.violations[:5]}"
        )

    def test_tape_is_substantial(self, clean_tape):
        assert clean_tape.count > 15000

    def test_tape_is_not_truncated(self, clean_tape):
        assert not clean_tape.is_truncated
        assert min(clean_tape.multipliers) == pytest.approx(1.0)

    def test_tape_is_clean(self, clean_tape):
        assert clean_tape.is_clean

    def test_rounds_are_chronological(self, rounds):
        stamps = [r["timestamp"] for r in rounds]
        assert stamps == sorted(stamps)

    def test_ids_are_unique(self, rounds):
        identifiers = [r["id"] for r in rounds]
        assert len(identifiers) == len(set(identifiers))

    def test_every_band_is_represented(self, multipliers):
        seen = {ling.band_for(m)["key"] for m in multipliers}
        assert seen == set(ling.BAND_KEYS), f"missing bands: {set(ling.BAND_KEYS) - seen}"


class TestPointsFormula:
    def test_points_column_is_the_momento_scaler(self, rounds):
        # Points is 100 + 30*log2(multiplier); confirming it on real rows proves
        # the export is generated by this codebase.
        for record in rounds[:2000]:
            assert record["points"] == pytest.approx(
                100.0 + 30.0 * math.log2(record["multiplier"]), abs=0.002
            )

    def test_unit_multiplier_maps_to_one_hundred_points(self):
        assert ling.to_points(1.0) == pytest.approx(100.0)

    def test_points_round_trip(self):
        for multiplier in (1.0, 2.0, 13.34, 633.49, 7119.14):
            assert ling.from_points(ling.to_points(multiplier)) == pytest.approx(
                multiplier, rel=1e-3
            )


class TestRowValidation:
    def _row(self, **overrides):
        row = {
            "ID": "58122",
            "Timestamp": "2026-07-28T20:20:30.575+00:00",
            "Multiplier": "13.34",
            "Color": "rgb(192, 23, 180)",
            "Band": "ignition",
            "Points": "212.131",
            "Ingest Method": "file",
        }
        row.update(overrides)
        return row

    def test_a_real_row_passes(self):
        result = loader.validate_row(self._row(), 2)
        assert result["problems"] == []
        assert result["round"]["band"] == "ignition"

    def test_mislabelled_band_is_caught(self):
        result = loader.validate_row(self._row(Band="moonshot"), 2)
        assert any("band" in p for p in result["problems"])

    def test_wrong_points_is_caught(self):
        result = loader.validate_row(self._row(Points="999.0"), 2)
        assert any("points" in p for p in result["problems"])

    def test_wrong_colour_is_caught(self):
        result = loader.validate_row(self._row(Color="rgb(52, 180, 255)"), 2)
        assert any("colour" in p for p in result["problems"])

    def test_sub_unit_multiplier_is_caught(self):
        result = loader.validate_row(
            self._row(Multiplier="0.5", Band="dust", Points="100.0"), 2
        )
        assert any("floor" in p for p in result["problems"])

    def test_unparseable_multiplier_yields_no_round(self):
        result = loader.validate_row(self._row(Multiplier="n/a"), 2)
        assert result["round"] is None
        assert result["problems"]


class TestTruncatedExportGuard:
    def test_truncated_export_is_detected_as_filtered(self):
        path = loader.repo_root() / loader.TRUNCATED_TAPE
        if not path.exists():
            pytest.skip("truncated export not present")

        result = loader.load_csv(path)
        assert result.is_truncated, (
            "the >=10x export must be recognised as filtered, otherwise fitting "
            "a distribution to it would silently produce a biased house edge"
        )
        assert min(result.multipliers) >= 10.0

    def test_truncated_export_is_a_subset_of_the_clean_tape(self, rounds):
        path = loader.repo_root() / loader.TRUNCATED_TAPE
        if not path.exists():
            pytest.skip("truncated export not present")

        subset = loader.load_csv(path)
        clean_by_id = {r["id"]: r["multiplier"] for r in rounds}
        for record in subset.rounds[:500]:
            assert record["id"] in clean_by_id, f"round {record['id']} missing from clean tape"
            assert clean_by_id[record["id"]] == pytest.approx(record["multiplier"])

    def test_merging_exports_removes_duplicates(self):
        root = loader.repo_root()
        clean = root / loader.CLEAN_TAPE
        truncated = root / loader.TRUNCATED_TAPE
        if not (clean.exists() and truncated.exists()):
            pytest.skip("both exports required")

        merged = loader.load_csv([clean, truncated])
        single = loader.load_csv(clean)
        # The truncated file adds no new rounds, only duplicates.
        assert merged.count == single.count
        assert merged.duplicates_removed > 1000

    def test_header_mismatch_is_rejected(self, tmp_path):
        bad = tmp_path / "bad.csv"
        bad.write_text("a,b,c\n1,2,3\n", encoding="utf-8")
        with pytest.raises(ValueError, match="unexpected header"):
            loader.load_csv(bad)

    def test_missing_file_is_rejected(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            loader.load_csv(tmp_path / "nope.csv")
