"""Load and validate Eagle Eye round exports.

The exports in the repository root are machine-generated by this codebase:
`Band`, `Color` and `Points` are pure functions of `Multiplier`, defined in
`momento.linguistics` as `band_for`, `color_for` and `to_points`. The loader
validates every row against those functions rather than trusting the file, so a
truncated, re-sorted or hand-edited export fails loudly instead of quietly
entering a backtest.

Two exports currently sit in the root:

* `eagle-eye-export-2026-07-28__1_.csv` — the clean full tape, every band.
* `eagle-eye-export-2026-07-28.csv` — the same data truncated to multipliers
  >= 10x. It is a labelled positive-class subset, so fitting a distribution to
  it would produce a badly biased estimate. `load_clean_tape` refuses it.
"""

from __future__ import annotations

import csv
import logging
import math
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

from momento import linguistics as ling

logger = logging.getLogger("research.loader")

__all__ = [
    "CLEAN_TAPE",
    "TRUNCATED_TAPE",
    "LoadResult",
    "TruncatedExportError",
    "load_clean_tape",
    "load_csv",
    "repo_root",
    "validate_row",
]

EXPECTED_HEADER = [
    "ID",
    "Timestamp",
    "Multiplier",
    "Color",
    "Band",
    "Points",
    "Ingest Method",
]

#: The collector writes CSS colours; `linguistics.color_for` returns names.
CSV_COLOUR_BY_NAME: Dict[str, str] = {
    "blue": "rgb(52,180,255)",
    "purple": "rgb(145,62,248)",
    "pink": "rgb(192,23,180)",
}

#: `Points` is rounded to three decimals by `to_points`.
POINTS_TOLERANCE = 0.002

#: A tape whose smallest multiplier sits at or above this is a filtered subset.
TRUNCATION_FLOOR = 2.0

CLEAN_TAPE = "eagle-eye-export-2026-07-28__1_.csv"
TRUNCATED_TAPE = "eagle-eye-export-2026-07-28.csv"


class TruncatedExportError(ValueError):
    """Raised when a filtered export is used where a full tape is required."""


@dataclass
class LoadResult:
    """Rounds plus everything needed to judge whether they can be trusted."""

    rounds: List[Dict[str, Any]] = field(default_factory=list)
    violations: List[Dict[str, Any]] = field(default_factory=list)
    duplicates_removed: int = 0
    source_files: List[str] = field(default_factory=list)

    @property
    def count(self) -> int:
        return len(self.rounds)

    @property
    def multipliers(self) -> List[float]:
        return [float(r["multiplier"]) for r in self.rounds]

    @property
    def is_truncated(self) -> bool:
        values = self.multipliers
        return bool(values) and min(values) >= TRUNCATION_FLOOR

    @property
    def is_clean(self) -> bool:
        return not self.violations and not self.is_truncated

    def summary(self) -> Dict[str, Any]:
        values = self.multipliers
        return {
            "rounds": self.count,
            "source_files": list(self.source_files),
            "duplicates_removed": self.duplicates_removed,
            "violations": len(self.violations),
            "first_violations": self.violations[:5],
            "min_multiplier": min(values) if values else None,
            "max_multiplier": max(values) if values else None,
            "first_timestamp": self.rounds[0]["timestamp"].isoformat() if self.rounds else None,
            "last_timestamp": self.rounds[-1]["timestamp"].isoformat() if self.rounds else None,
            "truncated": self.is_truncated,
            "clean": self.is_clean,
        }


def repo_root() -> Path:
    """Repository root, resolved from this file rather than the cwd."""
    return Path(__file__).resolve().parents[2]


def _normalise_colour(value: str) -> str:
    return "".join(str(value).split()).lower()


def _parse_timestamp(value: str) -> Optional[datetime]:
    text = str(value).strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(text)
    except ValueError:
        return None


def validate_row(row: Dict[str, str], line_number: int) -> Dict[str, Any]:
    """Check one export row against the semantic layer.

    Returns a dict with `round` (None when unparseable) and `problems`, a list
    of human-readable strings naming every field that disagrees with
    `momento.linguistics`.
    """
    problems: List[str] = []

    raw_multiplier = (row.get("Multiplier") or "").strip()
    try:
        multiplier = float(raw_multiplier)
    except (TypeError, ValueError):
        return {
            "round": None,
            "problems": [f"line {line_number}: unparseable multiplier {raw_multiplier!r}"],
        }

    if not math.isfinite(multiplier) or multiplier < 1.0:
        problems.append(f"line {line_number}: multiplier {multiplier} is below the 1.00x floor")

    timestamp = _parse_timestamp(row.get("Timestamp") or "")
    if timestamp is None:
        problems.append(f"line {line_number}: unparseable timestamp {row.get('Timestamp')!r}")

    try:
        round_id = int((row.get("ID") or "").strip())
    except (TypeError, ValueError):
        round_id = -1
        problems.append(f"line {line_number}: unparseable id {row.get('ID')!r}")

    expected_band = ling.band_for(multiplier)["key"]
    actual_band = (row.get("Band") or "").strip().lower()
    if actual_band != expected_band:
        problems.append(
            f"line {line_number}: band {actual_band!r} but {multiplier}x is {expected_band!r}"
        )

    expected_colour = CSV_COLOUR_BY_NAME.get(ling.color_for(multiplier))
    actual_colour = _normalise_colour(row.get("Color") or "")
    if expected_colour is not None and actual_colour != expected_colour:
        problems.append(
            f"line {line_number}: colour {actual_colour!r} but {multiplier}x is {expected_colour!r}"
        )

    expected_points = ling.to_points(multiplier)
    try:
        actual_points = float((row.get("Points") or "").strip())
    except (TypeError, ValueError):
        actual_points = float("nan")
        problems.append(f"line {line_number}: unparseable points {row.get('Points')!r}")
    else:
        if abs(actual_points - expected_points) > POINTS_TOLERANCE:
            problems.append(
                f"line {line_number}: points {actual_points} but {multiplier}x scales "
                f"to {expected_points}"
            )

    record = {
        "id": round_id,
        "timestamp": timestamp,
        # `created_at` keeps these rounds shape-compatible with momento.analysis.
        "created_at": timestamp.isoformat() if timestamp else None,
        "multiplier": multiplier,
        "band": expected_band,
        "points": expected_points,
        "ingest_method": (row.get("Ingest Method") or "").strip(),
    }
    return {"round": record, "problems": problems}


def load_csv(
    paths: Sequence[Path] | Path | str,
    strict: bool = False,
) -> LoadResult:
    """Load one or more exports into a single chronologically ordered tape.

    Rounds are deduplicated by `ID` and sorted oldest first, because the
    exports arrive newest first and any walk-forward test depends on real
    chronological order.

    Args:
        paths: One path, or several to merge.
        strict: Raise on the first invariant violation instead of collecting.
    """
    if isinstance(paths, (str, Path)):
        paths = [Path(paths)]

    result = LoadResult()
    by_id: Dict[int, Dict[str, Any]] = {}

    for path in paths:
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"export not found: {path}")

        result.source_files.append(path.name)
        with path.open(newline="", encoding="utf-8-sig") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames != EXPECTED_HEADER:
                raise ValueError(
                    f"{path.name}: unexpected header {reader.fieldnames!r}, "
                    f"expected {EXPECTED_HEADER!r}"
                )

            for line_number, row in enumerate(reader, start=2):
                checked = validate_row(row, line_number)
                if checked["problems"]:
                    if strict:
                        raise ValueError(f"{path.name}: {checked['problems'][0]}")
                    for problem in checked["problems"]:
                        result.violations.append({"file": path.name, "detail": problem})

                record = checked["round"]
                if record is None or record["timestamp"] is None:
                    continue

                key = record["id"]
                if key in by_id:
                    result.duplicates_removed += 1
                    continue
                by_id[key] = record

    result.rounds = sorted(by_id.values(), key=lambda r: (r["timestamp"], r["id"]))
    logger.info(
        "loaded %d rounds from %s (%d duplicates, %d violations)",
        result.count,
        ", ".join(result.source_files),
        result.duplicates_removed,
        len(result.violations),
    )
    return result


def load_clean_tape(root: Optional[Path] = None, strict: bool = False) -> LoadResult:
    """Load the clean full tape from the repository root.

    Raises `TruncatedExportError` if the resulting tape looks filtered, which
    guards against pointing this at the >= 10x export and drawing conclusions
    about a distribution from its own positive class.
    """
    base = Path(root) if root is not None else repo_root()
    result = load_csv(base / CLEAN_TAPE, strict=strict)

    if result.is_truncated:
        raise TruncatedExportError(
            f"{CLEAN_TAPE} has a minimum multiplier of {min(result.multipliers)}x, "
            "so it is a filtered subset rather than a full tape. Distribution and "
            "independence tests on truncated data are biased and must not be used."
        )

    if result.violations:
        logger.warning(
            "%s has %d invariant violations; review before trusting any result",
            CLEAN_TAPE,
            len(result.violations),
        )
    return result
